name: pid-usage
version: '0.1.0'
summary: Find CPU and RAM Utilization of a process
description: |
  A simple command line utility to find CPU and RAM Utilization within certain
  intervals for a given PID and all its subprocesses.
  Currently the output is CSV formatted.

base: core18
grade: stable
license: MIT
confinement: strict

parts:
  primary:
    plugin: cmake
    build-packages: [gcc, make]
    source: '.'

apps:
  pid-usage:
    command: pid-usage
